# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ddcfe6090f1536828110bc9dbf9bdb7a0c41654276957937ae79796a340caa7b37314e0cb3f6ad5c34b4a09295c26fe75e61b1f2fb115d8fff2c6c010c53a6f

test:
  secret_key_base: 39cd1ed415fcfec4e3e3f5c29752636ed0bcc915119659eae0c170caeadb73a6c93c09216bcd631ca42e7f22da76ccf4655464d704858fd1bd08a94ae3f443b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
